markdown: rdiscount
permalink: /:title/
url: http://angelof7.github.io
beian: 苏ICP备1500846
name: AndyStack
author: andygc
email: cgao886@163.com
duoshuo: andygc
cnzz: 1255174608
weibo: 2106155130
github: angelof7
highlighter: pygments
safe: true
paginate: 20
gems: [jekyll-paginate]
about: "AndyGao's Life Stack."
